name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: npm install

      - name: Test
        run: npm test

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Dispatch
        run: 'curl -u "thoughtsunificator:${{secrets.PAT_TOKEN}}" -X POST  -H "Accept: application/vnd.github.v3+json"  https://api.github.com/repos/thoughtsunificator/domodel-diary-web/dispatches -d "{\"event_type\":\"build\"}"'
